import { type } from "arktype";

const artifactKind = '"plugin" | "skill"';
const scope = '"catalog" | "shelf" | "legacy"';
const sourceCounts = type({ "clawhub-web": "number", "openclaw-control-ui": "number" });
const intentKind = '"company_product" | "generic_capability" | "ambiguous"';
const classification = type({
  "artifactKind?": artifactKind,
  "scope?": scope,
  weekStart: "number",
  weekEnd: "number",
  query: "string",
  intentKind,
  "companyProductName?": "string",
  confidence: "number",
  model: "string",
  modelVersion: "string",
  processedAt: "number",
});
const currentResult = type({
  id: "string",
  artifactKind,
  "nativeSkillId?": "string",
  "category?": "string",
  eligibilityReasons: "string[]",
  name: "string",
  displayName: "string",
  summary: "string | null",
  version: "string | null",
  url: "string",
  isOfficial: "boolean",
  isFeatured: "boolean",
  eligibleForFeatured: "boolean",
});
export const SearchInsightsReportSchema = type({
  artifactKind,
  scope: `${scope} | null`,
  window: {
    endDay: "number",
    start7d: "number",
    startPrevious7d: "number",
    start30d: "number",
    days: "7 | 30",
  },
  source: '"clawhub-web" | "openclaw-control-ui" | null',
  generatedAt: "number",
  totalQueries: "number",
  totalSearches7d: "number",
  sources7d: sourceCounts,
  truncated: "boolean",
  classificationStatus: '"available" | "partial" | "unavailable"',
  classificationRun: type({
    weekStart: "number",
    weekEnd: "number",
    processedAt: "number",
    expectedQualified: "number",
    classifiedCount: "number",
    truncated: "boolean",
    model: "string",
    modelVersion: "string",
    "failureCode?": "string",
  }).or("null"),
  metadataCheckedAt: "number | null",
  currentMetadataStatus: '"available" | "unavailable"',
  coverage: {
    dataThrough: "number | null",
    collectionStartedAt: "number | null",
    gapStart: "number | null",
    gapEnd: "number | null",
  },
  rows: type({
    artifactKind,
    scope,
    query: "string",
    searches7d: "number",
    searchesPrevious7d: "number",
    searches30d: "number",
    officialGaps7d: "number",
    officialGaps30d: "number",
    zeroResults7d: "number",
    change7d: "number",
    changePercent: "number | null",
    sources7d: sourceCounts,
    classification: classification.or("null"),
    companyOpportunity: "boolean",
    searchUrl: "string",
    currentResults: currentResult.array(),
    featuredCandidate: currentResult.or("null"),
  }).array(),
});

const adoptionEvidence = type({
  source: '"package-daily-installs" | "skill-daily-installs"',
  rank: "number",
  snapshotId: "string",
  rankingVersion: "string",
  periodStart: "number",
  periodStart7d: "number",
  periodEnd: "number",
  generatedAt: "number",
  installs30d: "number",
  installs7d: "number",
  importedRows: "number",
  importDatasetVersions: "string[]",
});

const featuredCandidate = type({
  id: "string",
  artifactKind,
  name: "string",
  displayName: "string",
  summary: "string | null",
  url: "string",
  category: "string | null",
  version: "string | null",
  "createdAt?": "number",
  eligibleForFeatured: "boolean",
  eligibilityReasons: "string[]",
  support: '"both" | "search-only" | "adoption-only" | "current-only"',
  adoption: adoptionEvidence.or("null"),
  search: type({
    matchedSearches7d: "number",
    previous7d: "number",
    searches30d: "number",
    omittedQueries: "number",
    periodStart: "number",
    periodEnd: "number",
    dataThrough: "number | null",
    collectionStartedAt: "number | null",
    queries: type({
      query: "string",
      scope,
      searches7d: "number",
      previous7d: "number",
      searches30d: "number",
    }).array(),
  }).or("null"),
});

export const FeaturedIntelligenceReportSchema = type({
  searchReport: SearchInsightsReportSchema,
  metadataCheckedAt: "number | null",
  adoption: {
    status: '"available" | "unavailable"',
    generatedAt: "number | null",
    collectionStartedAt: "number",
    periodStart: "number",
    periodStart7d: "number",
    periodEnd: "number",
    snapshotId: "string | null",
    rankingVersion: "string",
    totalItems: "number",
    inspectedItems: "number",
    scannedRows: "number",
    importedRows: "number",
    importDatasetVersions: "string[]",
    truncated: "boolean",
  },
  recommendations: {
    totalCandidates: "number",
    omittedCandidates: "number",
    excluded: type({
      id: "string",
      displayName: "string",
      url: "string",
      reasons: "string[]",
    }).array(),
    candidates: featuredCandidate.array(),
    lineup: {
      targetSize: "16",
      reservedSlots: "number",
      telemetryTarget: "number",
      editorialRevision: "number",
      currentEditorialRevision: "number",
      staleEditorial: "boolean",
      pendingCount: "number",
      telemetryShortfall: "number",
      reservations: type({
        slot: "number",
        id: "string | null",
        name: "string | null",
        displayName: "string | null",
        reason: "string | null",
        status: '"ready" | "pending"',
        pendingReasons: "string[]",
        artifact: featuredCandidate.or("null"),
      }).array(),
      baseline: type({ id: "string", version: "string | null", featuredAt: "number" }).array(),
      proposed: featuredCandidate
        .and({
          change: '"retain" | "add"',
          emerging: "boolean",
          slot: "number",
          selectionBasis: '"editorial" | "telemetry"',
          reason: "string",
        })
        .array(),
      removals: type({
        id: "string",
        displayName: "string",
        url: "string",
        reasons: "string[]",
      }).array(),
      shortfall: "number",
    },
  },
});
