import { type } from "arktype";

const artifactKind = '"plugin" | "skill"';
const scope = '"catalog" | "shelf" | "legacy"';
const sourceCounts = type({ "clawhub-web": "number", "openclaw-control-ui": "number" });
const intentKind = '"company_product" | "generic_capability" | "ambiguous"';
const classification = type({
  "artifactKind?": artifactKind,
  "scope?": scope,
  weekStart: "number",
  weekEnd: "number",
  query: "string",
  intentKind,
  "companyProductName?": "string",
  confidence: "number",
  model: "string",
  modelVersion: "string",
  processedAt: "number",
});
const currentResult = type({
  id: "string",
  artifactKind,
  "nativeSkillId?": "string",
  "category?": "string",
  eligibilityReasons: "string[]",
  name: "string",
  displayName: "string",
  summary: "string | null",
  version: "string | null",
  url: "string",
  isOfficial: "boolean",
  isFeatured: "boolean",
  eligibleForFeatured: "boolean",
});
export const SearchInsightsReportSchema = type({
  artifactKind,
  scope: `${scope} | null`,
  window: {
    endDay: "number",
    start7d: "number",
    startPrevious7d: "number",
    start30d: "number",
    days: "7 | 30",
  },
  source: '"clawhub-web" | "openclaw-control-ui" | null',
  generatedAt: "number",
  totalQueries: "number",
  totalSearches7d: "number",
  sources7d: sourceCounts,
  truncated: "boolean",
  classificationStatus: '"available" | "partial" | "unavailable"',
  classificationRun: type({
    weekStart: "number",
    weekEnd: "number",
    processedAt: "number",
    expectedQualified: "number",
    classifiedCount: "number",
    truncated: "boolean",
    model: "string",
    modelVersion: "string",
    "failureCode?": "string",
  }).or("null"),
  metadataCheckedAt: "number | null",
  currentMetadataStatus: '"available" | "unavailable"',
  coverage: {
    dataThrough: "number | null",
    collectionStartedAt: "number | null",
    gapStart: "number | null",
    gapEnd: "number | null",
  },
  rows: type({
    artifactKind,
    scope,
    query: "string",
    searches7d: "number",
    searchesPrevious7d: "number",
    searches30d: "number",
    officialGaps7d: "number",
    officialGaps30d: "number",
    zeroResults7d: "number",
    change7d: "number",
    changePercent: "number | null",
    sources7d: sourceCounts,
    classification: classification.or("null"),
    companyOpportunity: "boolean",
    searchUrl: "string",
    currentResults: currentResult.array(),
    featuredCandidate: currentResult.or("null"),
  }).array(),
});

const adoptionEvidence = type({
  source: '"package-trending" | "clawhub-trending" | "clawhub-rising" | "skills-sh-trending"',
  rank: "number",
  snapshotId: "string",
  rankingVersion: "string",
  periodStart: "number | null",
  periodEnd: "number | null",
  generatedAt: "number",
  sourceObservedAt: "number | null",
  downloads: "number | null",
  installs: "number | null",
  bookmarks: "number | null",
  lifetimeInstalls: "number | null",
});

export const FeaturedIntelligenceReportSchema = type({
  searchReport: SearchInsightsReportSchema,
  metadataCheckedAt: "number | null",
  adoption: {
    status: '"available" | "unavailable"',
    generatedAt: "number | null",
    periodStart: "number | null",
    periodEnd: "number | null",
    snapshotId: "string | null",
    rankingVersion: "string | null",
    totalItems: "number",
    inspectedItems: "number",
    truncated: "boolean",
  },
  recommendations: {
    totalCandidates: "number",
    omittedCandidates: "number",
    excluded: type({
      id: "string",
      displayName: "string",
      url: "string",
      reasons: "string[]",
    }).array(),
    candidates: type({
      id: "string",
      artifactKind,
      name: "string",
      displayName: "string",
      summary: "string | null",
      url: "string",
      category: "string | null",
      eligibleForFeatured: "boolean",
      eligibilityReasons: "string[]",
      support: '"both" | "search-only" | "adoption-only"',
      adoption: adoptionEvidence.or("null"),
      search: type({
        matchedSearches7d: "number",
        previous7d: "number",
        searches30d: "number",
        omittedQueries: "number",
        periodStart: "number",
        periodEnd: "number",
        dataThrough: "number | null",
        collectionStartedAt: "number | null",
        queries: type({
          query: "string",
          scope,
          searches7d: "number",
          previous7d: "number",
          searches30d: "number",
        }).array(),
      }).or("null"),
    }).array(),
  },
});
